"""empty message

Revision ID: 169422a3a965
Revises: 560776fb268b
Create Date: 2014-08-24 16:50:45.460022

"""

# revision identifiers, used by Alembic.
revision = '169422a3a965'
down_revision = '560776fb268b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('candidate_A_namename', sa.String(length=255), nullable=True))
    op.add_column('match', sa.Column('candidate_B_namename', sa.String(length=255), nullable=True))
    op.drop_column('match', 'candidate_B_name')
    op.drop_column('match', 'candidate_A_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('candidate_A_name', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('candidate_B_name', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('match', 'candidate_B_namename')
    op.drop_column('match', 'candidate_A_namename')
    ### end Alembic commands ###
