"""empty message

Revision ID: 31892ef77d8c
Revises: 177ebe91a4b4
Create Date: 2014-09-07 22:19:57.737116

"""

# revision identifiers, used by Alembic.
revision = '31892ef77d8c'
down_revision = '177ebe91a4b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('candidate_A_photolink', sa.String(length=255), nullable=True))
    op.add_column('match', sa.Column('candidate_A_school', sa.String(length=255), nullable=True))
    op.add_column('match', sa.Column('candidate_B_photolink', sa.String(length=255), nullable=True))
    op.add_column('match', sa.Column('candidate_B_school', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'candidate_B_school')
    op.drop_column('match', 'candidate_B_photolink')
    op.drop_column('match', 'candidate_A_school')
    op.drop_column('match', 'candidate_A_photolink')
    ### end Alembic commands ###
