"""empty message

Revision ID: 51a0994e6170
Revises: None
Create Date: 2014-08-24 16:47:41.708512

"""

# revision identifiers, used by Alembic.
revision = '51a0994e6170'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
