"""empty message

Revision ID: 52ae7c3a3577
Revises: None
Create Date: 2014-08-24 13:09:39.744433

"""

# revision identifiers, used by Alembic.
revision = '52ae7c3a3577'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.drop_table('candi__match')
    op.drop_column('user', '_id')
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('user', sa.Column('_id', mysql.VARCHAR(length=255), nullable=False))
    op.create_table('candi__match',
    sa.Column('match_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('match')
    ### end Alembic commands ###
