"""empty message

Revision ID: 54b7c30dee9a
Revises: None
Create Date: 2014-08-25 20:37:43.726000

"""

# revision identifiers, used by Alembic.
revision = '54b7c30dee9a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('comment',
    sa.Column('Comment_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('likecount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Comment_id')
    )
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('candidate_A_namename', sa.String(length=255), nullable=True),
    sa.Column('candidate_A_count', sa.Integer(), nullable=False),
    sa.Column('candidate_B_namename', sa.String(length=255), nullable=True),
    sa.Column('candidate_B_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('candidate')
    ### end Alembic commands ###
