"""empty message

Revision ID: 560776fb268b
Revises: 51a0994e6170
Create Date: 2014-08-24 16:49:09.336935

"""

# revision identifiers, used by Alembic.
revision = '560776fb268b'
down_revision = '51a0994e6170'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
